README.md, examples/default/README.md, examples/non-default/README.md
Update Examples section of README
=> docs: Update Examples section of README

.releaserc, catalogValidationValues.json.template
updates required for catalog onboarding
=> ci: updates required for catalog onboarding

README.md, version.tf
fix: update required_version format so it is compatible with current regex check in catalog pipeline
=> fix: update required_version format

.releaserc
ci: add missing comma in .releaserc
=> ci: add missing comma in .releaserc

.github/workflows/ci.yml, .github/workflows/release.yml, .releaserc
=> ci: override catalog apikeys

.releaserc
ci: updated .releaserc to publish to SAP account
=> ci: updated .releaserc to publish to SAP account

.secrets.baseline, README.md
I'm not sure that I interpreted the `input.tfvars` usage correctly. Please help me get it correct. 
(After the text approved, I'll update the other references in the examples.)
- Moved the content from the 2nd `usage` section to the top.
- Removed the content about overriding default variable values. That seems like standard Terraform behavior.
- Added some missing sections
- iam permissions statement
- contributing section
- Editorial updates
=> docs: update readme file

variables.tf
Suggestions for variable descriptions.
Would merge into https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/pull/34
=> updated descriptions in variables.tf

ibm_catalog.json
Fold in changes from Content for architecture diagram description to keep from losing them.
- [x ] Documentation update
=> docs: fold in Content updates for description

.releaserc
Remove `--validation_dir_list` flag so the pipeline parses the ibm_catalog.json file
=> ci: remove --validation_dir_list flag

README.md, main.tf, module-metadata.json, version.tf
Please include a summary of the change and which issue is fixed. Also, please include the motivation and context for the change. List any dependencies that are required for this change.
=> fix: add sleep for squid setup

tests/pr_test.go
Enable the upgrade test for pull request unit tests. This will run a special test to verify changes between master and PR branch.
=> test: enable upgrade test for pull request CI

ibm_catalog.json
Update the catalog json file to use the newer schema that was pushed to prod Oct 31.  No functional changes to this repo.  This is for consistency with the other repos that have a catalog json file so that they may all be processed the same way by the publish pipeline.
- [ x] Documentation update
=> docs: update catalog json file to use new schema

ibm_catalog.json
add needed type specification to architecture diagram in catalog manifest
- [ x] CI related update (pipeline, etc.)
=> ci: fix architecture image spec in catalog manifest

.secrets.baseline, ibm_catalog.json
The local usage string was not complete.
- [ x] Documentation update
=> docs: provide complete usage string

ibm_catalog.json
Update permissions that will be displayed on the catalog tile.
- [x ] Documentation update
=> docs: update needed deploy permissions

module-metadata.json, submodules/power_management_services_setup/main.tf
Bug_fix: Fix ansible file var path causing ansible playbook to fail
---
=> fix: fix file_path

.secrets.baseline, README.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md
- Adds a link to the reference architecture from the main readme file
- reference-architecture
- makes all the anchor attributes unique
- updates final table caption
GitHub issue: related to https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/issues/344
---
The commit message determines whether a new version of the module is needed, and if …
=> updates for ref arch

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
Updates the ref arch in #357 
- Update anchors to make sure they are unique within the repo
- Try to simplify description
- Style and word usage changes
These changes are not meant to change the meaning or accuracy, so please check for that.
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use …
=> Update to ref arch

ibm_catalog.json
Remove the profile from CRA in catalog.json file
=> docs: remove ac-4 scan profile

.secrets.baseline, ibm_catalog.json
Add fullstack property to the ibm_catalog.json file for the two flavors.
- [ x] CI-related update (pipeline, etc.)
---
=> ci: add fullstack designation to flavors

ibm_catalog.json
Remove the scan profile from extension flavour
---
=> ci: remove scan profile

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
=> Ref arch changes2

examples/ibm-catalog/deployable-architectures/full-stack/README.md, examples/ibm-catalog/deployable-architectures/full-stack/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
=> merge : main to dev

examples/ibm-catalog/deployable-architectures/full-stack/README.md, examples/ibm-catalog/deployable-architectures/full-stack/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
=> merge: main to dev

ibm_catalog.json
Change flavor names for extension and fullstack install types to be the same.  Note this includes both the `name` and `label` properties.
By doing this, the catalog consumption UI will present both with an option to "create a new architecture" or "extend an existing SLZ".
Its important the the names match as well as the labels match.
- [x ] Documentation update
--- …
=> Same flavor name in ibm_catalog.json

.secrets.baseline, ibm_catalog.json
This is a slimmed down version of the configuration of the deployment variables.  Removed were the duplicate information that is also in the variables.tf file which should be the source of truth.  Configuration was retained for all the variables so that their order would be preserved in the catalog consumption UI.
Descriptions, default values, etc. to come from the variables.tf file.
- [ x] Documentation update
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents …
=> docs: remove duplicate info from variables in manifest

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md
=> docs: Update deploy-arch-ibm-pvs-inf-extension.md

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md
=> add toc version to extension ref arch

ibm_catalog.json
=> docs: set required true for extesnion variables

reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
Add `production` flag in reference architecture markdown file.
---
=> add metadata to reference architecture

ibm_catalog.json
Updating the compliance to sccv3 and IBM cloud Financial services 1.2
---
=> docs: catalog sccv3

README.md, examples/ibm-catalog/deployable-architectures/extension/README.md, examples/ibm-catalog/deployable-architectures/extension/outputs.tf, examples/ibm-catalog/deployable-architectures/full-stack/README.md, examples/ibm-catalog/deployable-architectures/full-stack/outputs.tf, examples/terraform-registry/extension/README.md, examples/terraform-registry/extension/outputs.tf, ibm_catalog.json, module-metadata.json, outputs.tf, submodules/power_workspace/README.md, submodules/power_workspace/main.tf, submodules/power_workspace/outputs.tf, submodules/terraform_templates/services_init.sh.tftpl
Update the services_init.sh.tfpl file to handle OS registration on SLES efficiently. Source the /etc/bash.bashrc helps in mitigating the issue
---
=> fix: os registration sles

submodules/terraform_templates/install_packages.sh.tftpl
Remove the $ in script to install awscli package on intel machine
---
=> fix: zypper install awscli

examples/ibm-catalog/deployable-architectures/extension/README.md, examples/ibm-catalog/deployable-architectures/extension/main.tf, examples/ibm-catalog/deployable-architectures/extension/outputs.tf, examples/ibm-catalog/deployable-architectures/extension/variables.tf, ibm_catalog.json, tests/pr_test.go
Modify catalog json file and also remove the ssh_private_key variable from extension flavour.
The extension flavour was modified to use the PowerVS full-stack solution as pre-requisite infrastructure. This enables more than one PowerVS Workspaces to use same VPC landing zone. VSI on VPC landing zone dependency for extension flavour has been removed.
---
The commit …
=> feat: upgrade catalog json file

ibm_catalog.json
Update feature in json manifest file
---
=> docs: update feature

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md
Sync the description of fullstack and extension solution
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message …
=> docs: update description

tests/pr_test.go
tests remove default region
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …
=> ci: tests remove default region

ibm_catalog.json
Add correct variables for work with CLI section in catalog
Run the CI pipeline when the PR is ready for review and you …
=> docs: catalog cli update vars

solutions/ibm-catalog/deployable-architectures/extension/main.tf, solutions/ibm-catalog/deployable-architectures/extension/outputs.tf
fix: extension variables  nfs,ntp and dns output variable to output if enabled from fullstack solution else output empty string
If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the …
=> fix: extension output variables

.github/settings.yml, .github/workflows/ci.yml, .github/workflows/release.yml, README.md
- migrate to v2 pipeline
- remove build status badge (no longer applicable with new pipeline)
NOTE: This PR will have to be force merged, as pipeline will not run until it is merged to main branch
If the CI pipeline doesn't run when you create the PR, …
=> ci: migrate to v2 pipeline

.secrets.baseline, ibm_catalog.json
Remove scans from extension flavour as Power doesnt support it.
Run the CI pipeline when the PR is ready for review and …
=> docs: remove scans from extension flavour

ibm_catalog.json, solutions/full-stack/main.tf, solutions/quickstart/main.tf
fixes: Invalid value for "path" parameter: no file exists at "./../../presets/slz-for-powervs/rhel-vpc-pvs.preset.json.tftpl"; this function works only with files that are distributed as
part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this result from an attribute of that resource.
Your …
=> fix: use absolute path instead of relative path

reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
[https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob[…]-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob/main/reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md)
Power Virtual Server with VPC landing zone - as  quickstart deployment
[https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob[…]-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob/main/reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md)
Power Virtual Server with VPC landing zone - as PowerVS workspace deployment
If the CI pipeline …
=> docs: rename titles

cra-config.yaml
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
=> ci: fix  cra scan resource group

.github/settings.yml
=> ci: update repo description

README.md, modules/powervs-vpc-landing-zone/README.md, solutions/extension/README.md, solutions/full-stack/README.md, solutions/quickstart/README.md
fix: broken links in docs
```
/run pipeline
```
=> docs: update broken links

.github/settings.yml, .secrets.baseline, ibm_catalog.json
- add repo topics
- remove `usage_template` from catalog manifest. DAs are not designed to be embedded into part of another DA solution, they are designed to be the top level solution and not called from any higher level. So in this PR, I am removing the `usage_template` from the DA manifest which means the DA will no long show the `Embed code` section in the UI:
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging …
=> ci: add repo topics + remove usage_template from catalog manifest

.catalog-onboard-pipeline.yaml, ibm_catalog.json, solutions/import-workspace/module/acl/README.md, solutions/import-workspace/module/acl/main.tf, solutions/import-workspace/module/security-group/README.md, solutions/import-workspace/module/security-group/main.tf, solutions/import-workspace/module/security-group/variables.tf, solutions/import-workspace/outputs.tf
=> Catalog prov

README.md, modules/powervs-vpc-landing-zone/presets/acl_rules.json.tftpl, modules/powervs-vpc-landing-zone/presets/sg_rules.json.tftpl, solutions/import-workspace/README.md, solutions/import-workspace/import_vpc.tf, solutions/import-workspace/locals_vpc.tf, solutions/import-workspace/module/powervs/outputs.tf, solutions/import-workspace/module/security-group/README.md, solutions/import-workspace/module/vpc/README.md, solutions/import-workspace/module/vpc/main.tf, solutions/import-workspace/module/vpc/variables.tf, solutions/import-workspace/outputs.tf, solutions/import-workspace/variables.tf
=> Acl sg presets

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
Update versions for cloud docs
```
/run pipeline
```
=> docs: fix versions for cloud docs

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
update toc version for cloud docs
```
/run pipeline
```
=> docs: update toc version

README.md, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
Doc Updates
```
/run pipeline
```
=> feat: doc updates

ibm_catalog.json, solutions/extension/README.md, solutions/extension/versions.tf, solutions/full-stack/README.md, solutions/full-stack/versions.tf, solutions/import-workspace/README.md, solutions/import-workspace/versions.tf, solutions/quickstart/README.md, solutions/quickstart/versions.tf
=> feat: enable mad02 DC and new variation import workspace

solutions/extension/README.md, solutions/extension/versions.tf, solutions/full-stack/README.md, solutions/full-stack/versions.tf, solutions/import-workspace/README.md, solutions/import-workspace/versions.tf, solutions/quickstart/README.md, solutions/quickstart/versions.tf
=> feat: upgrade tf version to 1.60.0

ibm_catalog.json
=> ci: catalog_json defaults fix

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
switch eu-de-1 to PER category.
:warning:  :warning:   :warning:
If solution was deployed using previous versions in powervs zone eu-de-1, please do not update to this version as it will corrupt your landscape. Use this solution for new deployments in eu-de-1 region. If deployed in other powervs_zone it can be upgraded without any issue. 
```
/run pipeline
```
- Include …
=> feat: switch eu-de-1 to PER category

solutions/extension/README.md, solutions/extension/main.tf
update powervs workspace version to 1.5.0
```
/run pipeline
```
=> fix: extension workspace version

ibm_catalog.json
=> ci: add Dcs to extension variation

reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, solutions/import-workspace/README.md
- Added a note in README for ACL rule quota and 
- Included the architecture diagram in the README 
```
/run pipeline
```
=> docs: note for import-workspace

solutions/full-stack/README.md
=> docs: add tf_docs content to solutions/full-stack

modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/extension/README.md, solutions/extension/main.tf
switch sao01 to PER DC
```
/run pipeline
```
=> feat: switch sao01 to PER DC

ibm_catalog.json
update catalog_json
```
/run pipeline
```
=> ci: update catalog_json

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/extension/README.md, solutions/extension/main.tf, solutions/extension/versions.tf, solutions/full-stack/README.md, solutions/full-stack/versions.tf, solutions/import-workspace/README.md, solutions/import-workspace/versions.tf, solutions/quickstart/README.md, solutions/quickstart/versions.tf
IBM terraform provider updated to 1.63.0
PER enabled for DC location tok04
```
/run pipeline
```
=> feat: 282 tok04 per

solutions/full-stack/catalogValidationValues.json.template, solutions/quickstart/README.md, solutions/quickstart/catalogValidationValues.json.template, solutions/quickstart/main.tf
upgrade powervs instance version to 1.1.0
```
/run pipeline
```
=> fix: upgrade instance version to 1.1.0

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> docs: release notes v4.6.1

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/extension/README.md, solutions/extension/main.tf
switch osa21 to PER DC
```
/run pipeline
```
=> feat: switch osa21 to PER DC

cra-config.yaml, ibm_catalog.json
update DAs to claim SCC profile "IBM Cloud Framework for Financial Services" version 1.6.0 since older versions are now depricated.
(NOTE: The name of the profile changed since 1.3.0)
```
/run pipeline
```
- Use the **Squash and merge** …
=> update DAs to claim SCC profile "IBM Cloud Framework for Financial Services" version 1.6.0

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/extension/README.md, solutions/extension/main.tf
switch lon06 to PER DC
```
/run pipeline
```
=> feat: switch lon06 to PER DC

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/extension/README.md, solutions/extension/main.tf, solutions/quickstart/locals.tf, solutions/quickstart/variables.tf
switch tor01 and us-south DC to PER DC; provided sles in quicks…
```
/run pipeline
```
=> feat: switch tor01 and us-south DC to PER DC

ibm_catalog.json
fix json file
```
/run pipeline
```
=> ci: catalog json update images

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> docs: set prod to false as not yet gaed

ibm_catalog.json, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/full-stack/provider.tf, solutions/quickstart/provider.tf
add condition for secrets manager provider
```
/run pipeline
```
=> fix: provider for vpn and dropdown config in json

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/client2sitevpn.tf, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> fix: upgrade sm versions

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> docs: set prod to true for new arch

reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> docs: update ref arch version

ibm_catalog.json, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md
=> ci: fix defaults catalog json file

ibm_catalog.json
=> ci: fix defaults catalog json default value

ibm_catalog.json, modules/powervs-vpc-landing-zone/submodules/ansible/ansible_node_packages.sh, reference-architectures/extension/deploy-arch-ibm-pvs-inf-extension.md, reference-architectures/full-stack/deploy-arch-ibm-pvs-inf-full-stack.md, reference-architectures/import-workspace/deploy-arch-ibm-pvs-inf-import-workspace.md, reference-architectures/quickstart/deploy-arch-ibm-pvs-inf-quickstart.md, solutions/quickstart/README.md, solutions/quickstart/main.tf
update ansible role version
```
/run pipeline
```
=> fix: update ansible role version

tests/common-go-assets/cloudinfo-region-power-prefs.yaml, tests/pr_test.go
Include tests for Quickstart in the Infra repo along with the existing tests
```
/run pipeline
```
=> Test quickstart

ibm_catalog.json
Marked the extension DA as optional.
This is needed because catalog pushed a changed where by default, optional is now true.
```
/run pipeline
```
=> Marked the extension DA as optional

ibm_catalog.json
Update DOC link and remove NON per support
```
/run pipeline
```
=> docs: update docs url and remove mon01 and lon04 location

.secrets.baseline, ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/locals.tf, modules/powervs-vpc-landing-zone/main.tf, modules/powervs-vpc-landing-zone/outputs.tf, modules/powervs-vpc-landing-zone/presets/slz-preset.json.tftpl, modules/powervs-vpc-landing-zone/variables.tf, solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/catalogValidationValues.json.template, solutions/standard-plus-vsi/main.tf, solutions/standard-plus-vsi/outputs.tf, solutions/standard-plus-vsi/variables.tf, solutions/standard/README.md, solutions/standard/catalogValidationValues.json.template, solutions/standard/main.tf, solutions/standard/outputs.tf, solutions/standard/variables.tf, tests/pr_test.go
=> fix:  outputs, ibm_catalog.json, readme, tests

modules/powervs-vpc-landing-zone/locals.tf, modules/powervs-vpc-landing-zone/presets/slz-preset.json.tftpl, modules/powervs-vpc-landing-zone/submodules/ansible/ansible_node_packages.sh, modules/powervs-vpc-landing-zone/submodules/ansible/templates-ansible/configure-monitoring-instance/playbook-configure-monitoring-instance.yml.tftpl, modules/powervs-vpc-landing-zone/submodules/ansible/templates-ansible/configure-network-services/playbook-configure-network-services.yml.tftpl
=> feat: upgrade roles; upgrade OS image

modules/powervs-vpc-landing-zone/main.tf, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md
=> fix: inventory file names

modules/powervs-vpc-landing-zone/outputs.tf, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md
=> fix: expose monitoring host ip in outputs

modules/powervs-vpc-landing-zone/main.tf, modules/powervs-vpc-landing-zone/submodules/ansible/README.md, modules/powervs-vpc-landing-zone/submodules/ansible/ansible_node_packages.sh, modules/powervs-vpc-landing-zone/submodules/ansible/main.tf, modules/powervs-vpc-landing-zone/submodules/ansible/variables.tf, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md, solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/main.tf
=> fix: remove ansible collection version dependencies

modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/client2sitevpn.tf, modules/powervs-vpc-landing-zone/main.tf, solutions/import/README.md, solutions/import/versions.tf, solutions/standard-extend/README.md, solutions/standard-extend/main.tf, solutions/standard-extend/versions.tf, solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/versions.tf, solutions/standard/README.md, solutions/standard/versions.tf
=> chore: update modules; ci dependencies; tf version

ibm_catalog.json
=> docs: upgrade scc version to 1.7.0

ibm_catalog.json, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md
=> chore: update version

reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md
=> chore: reference arch

ibm_catalog.json, modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/client2sitevpn.tf, modules/powervs-vpc-landing-zone/main.tf, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md, solutions/import/README.md, solutions/import/versions.tf, solutions/standard-extend/README.md, solutions/standard-extend/main.tf, solutions/standard-extend/versions.tf, solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/versions.tf, solutions/standard/README.md, solutions/standard/versions.tf, tests/common-go-assets/cloudinfo-region-power-prefs.yaml
=> fix: upgrade tf provider

ibm_catalog.json, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md, solutions/standard-extend/README.md, solutions/standard-extend/outputs.tf
=> fix: remove undefined output for scc access key

cra-config.yaml, ibm_catalog.json
=> chore: update multiline secure value keys for projects

.secrets.baseline, cra-config.yaml, tests/pr_test.go
Add new secret for ansible vault password to include scc workload protection in cra scan and test pipeline
```
/run pipeline
```
=> chore: add ansible vault password for pipeline and cra scan

ibm_catalog.json, reference-architectures/import/deploy-arch-ibm-pvs-inf-import.md, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md
=> chore: version update

solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/variables.tf, solutions/standard/README.md, solutions/standard/variables.tf
=> chore: upgrade intel images

ibm_catalog.json, reference-architectures/standard-extend/deploy-arch-ibm-pvs-inf-standard-extend.md, reference-architectures/standard-plus-vsi/deploy-arch-ibm-pvs-inf-standard-plus-vsi.md, reference-architectures/standard/deploy-arch-ibm-pvs-inf-standard.md, solutions/standard-plus-vsi/main.tf
https://github.com/terraform-ibm-modules/powervs-sap-e2e-tests/actions/runs/15707138737/job/44255570286
If Load balancer fails, then server config is not executed yet.
However Aix_init doesn't depend on the module.standard to finish and rushes to export proxy , but then proxy server is not yet executed and whole deployment fails on first and second execution.
Would need 3 tries to finish. 
Adding explicit depends on for aix_init and scc_wp module
```
/run pipeline
```
- Use a conventional commit message to set the release level. …
=> fix: add depends_on for aix_init

modules/powervs-vpc-landing-zone/submodules/ansible/ansible_node_packages.sh
=> fix: print time and vsi id during ansible host setup

modules/powervs-vpc-landing-zone/presets/slz-preset.json.tftpl
Added New Schematics address.
```
/run pipeline
```
=> chore: Toronto Public ip added

modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/main.tf, solutions/standard-extend/README.md, solutions/standard-extend/main.tf
=> chore(deps): upgrade powervs workspace module to 3.2.0

modules/powervs-vpc-landing-zone/README.md, modules/powervs-vpc-landing-zone/powervs-ws.tf, solutions/standard-extend/README.md, solutions/standard-extend/main.tf, solutions/standard-plus-vsi/README.md, solutions/standard-plus-vsi/main.tf
* upgrade powervs workspace to v3.2.1
* upgrade powervs instance to 2.7.0
Note: Turning this one into a breaking change since the last one accidentally wasn't
```
/run pipeline
```
=> fix: upgrade powervs workspace to v3.2.1 and powervs instance to 2.7.0
